# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Verb.create(infinitive: 'abide', simple_past: 'abode', past_participle: 'abode')
Verb.create(infinitive: 'arise', simple_past: 'arose', past_participle: 'arisen')
Verb.create(infinitive: 'awake', simple_past: 'awoke', past_participle: 'awoken')
Verb.create(infinitive: 'be', simple_past: 'was, were', past_participle: 'been')
Verb.create(infinitive: 'bear', simple_past: 'bore', past_participle: 'borne / born')
Verb.create(infinitive: 'beat', simple_past: 'beat', past_participle: 'beaten')
Verb.create(infinitive: 'become', simple_past: 'became', past_participle: 'become')
Verb.create(infinitive: 'beget', simple_past: 'begat / begot', past_participle: 'begotten')
Verb.create(infinitive: 'begin', simple_past: 'began', past_participle: 'begun')
Verb.create(infinitive: 'bend', simple_past: 'bent', past_participle: 'bent')
Verb.create(infinitive: 'bereave', simple_past: 'bereft / bereaved', past_participle: 'bereft / bereaved')
Verb.create(infinitive: 'bet', simple_past: 'bet', past_participle: 'bet')
Verb.create(infinitive: 'bid', simple_past: 'bid / bade', past_participle: 'bid / bidden')
Verb.create(infinitive: 'bleed', simple_past: 'bled', past_participle: 'bled')
Verb.create(infinitive: 'blow', simple_past: 'blew', past_participle: 'blown')
Verb.create(infinitive: 'break', simple_past: 'broke', past_participle: 'broken')
Verb.create(infinitive: 'breed', simple_past: 'bred', past_participle: 'bred')
Verb.create(infinitive: 'bring', simple_past: 'brought', past_participle: 'brought')
Verb.create(infinitive: 'broadcast', simple_past: 'broadcast', past_participle: 'broadcast')
Verb.create(infinitive: 'build', simple_past: 'built', past_participle: 'built')
Verb.create(infinitive: 'burn', simple_past: 'burnt / burned', past_participle: 'burnt / burned')
Verb.create(infinitive: 'burst', simple_past: 'burst', past_participle: 'burst')
Verb.create(infinitive: 'buy', simple_past: 'bought', past_participle: 'bought')
Verb.create(infinitive: 'can', simple_past: 'could', past_participle: 'could')
Verb.create(infinitive: 'cast', simple_past: 'cast', past_participle: 'cast')
Verb.create(infinitive: 'catch', simple_past: 'caught', past_participle: 'caught')
Verb.create(infinitive: 'chide', simple_past: 'chid', past_participle: 'chiden')
Verb.create(infinitive: 'choose', simple_past: 'chose', past_participle: 'chosen')
Verb.create(infinitive: 'cling', simple_past: 'clung', past_participle: 'clung')
Verb.create(infinitive: 'clothe', simple_past: 'clad / clothed', past_participle: 'clad / clothed')
Verb.create(infinitive: 'come', simple_past: 'came', past_participle: 'come')
Verb.create(infinitive: 'cost', simple_past: 'cost', past_participle: 'cost')
Verb.create(infinitive: 'creep', simple_past: 'crept', past_participle: 'crept')
Verb.create(infinitive: 'cut', simple_past: 'cut', past_participle: 'cut')
Verb.create(infinitive: 'deal', simple_past: 'dealt', past_participle: 'dealt')
Verb.create(infinitive: 'dig', simple_past: 'dug', past_participle: 'dug')
Verb.create(infinitive: 'dive', simple_past: 'dived', past_participle: 'dived / dove')
Verb.create(infinitive: 'do', simple_past: 'did', past_participle: 'done')
Verb.create(infinitive: 'draw', simple_past: 'drew', past_participle: 'drawn')
Verb.create(infinitive: 'dream', simple_past: 'dreamt / dreamed', past_participle: 'dreamt / dreamed')
Verb.create(infinitive: 'drink', simple_past: 'drank', past_participle: 'drunk')
Verb.create(infinitive: 'drive', simple_past: 'drove', past_participle: 'driven')
Verb.create(infinitive: 'dwell', simple_past: 'dwelt', past_participle: 'dwelt / dwelled')
Verb.create(infinitive: 'eat', simple_past: 'ate', past_participle: 'eaten')
Verb.create(infinitive: 'fall', simple_past: 'fell', past_participle: 'fallen')
Verb.create(infinitive: 'feed', simple_past: 'fed', past_participle: 'fed')
Verb.create(infinitive: 'feel', simple_past: 'felt', past_participle: 'felt')
Verb.create(infinitive: 'fight', simple_past: 'fought', past_participle: 'fought')
Verb.create(infinitive: 'find', simple_past: 'found', past_participle: 'found')
Verb.create(infinitive: 'flee', simple_past: 'fled', past_participle: 'fled')
Verb.create(infinitive: 'fling', simple_past: 'flung', past_participle: 'flung')
Verb.create(infinitive: 'fly', simple_past: 'flew', past_participle: 'flown')
Verb.create(infinitive: 'forbid', simple_past: 'forbade', past_participle: 'forbidden')
Verb.create(infinitive: 'forecast', simple_past: 'forecast', past_participle: 'forecast')
Verb.create(infinitive: 'forget', simple_past: 'forgot', past_participle: 'forgotten / forgot')
Verb.create(infinitive: 'forgive', simple_past: 'forgave', past_participle: 'forgiven')
Verb.create(infinitive: 'forsake', simple_past: 'forsook', past_participle: 'forsaken')
Verb.create(infinitive: 'forsee', simple_past: 'foresaw', past_participle: 'foresawn')
Verb.create(infinitive: 'freeze', simple_past: 'froze', past_participle: 'frozen')
Verb.create(infinitive: 'get', simple_past: 'got', past_participle: 'gotten / got')
Verb.create(infinitive: 'give', simple_past: 'gave', past_participle: 'given')
Verb.create(infinitive: 'go', simple_past: 'went', past_participle: 'gone')
Verb.create(infinitive: 'grind', simple_past: 'ground', past_participle: 'ground')
Verb.create(infinitive: 'grow', simple_past: 'grew', past_participle: 'grown')
Verb.create(infinitive: 'hang', simple_past: 'hung', past_participle: 'hung')
Verb.create(infinitive: 'have', simple_past: 'had', past_participle: 'had')
Verb.create(infinitive: 'hear', simple_past: 'heard', past_participle: 'heard')
Verb.create(infinitive: 'hide', simple_past: 'hid', past_participle: 'hidden')
Verb.create(infinitive: 'hit', simple_past: 'hit', past_participle: 'hit')
Verb.create(infinitive: 'hold', simple_past: 'held', past_participle: 'held')
Verb.create(infinitive: 'hurt', simple_past: 'hurt', past_participle: 'hurt')
Verb.create(infinitive: 'keep', simple_past: 'kept', past_participle: 'kept')
Verb.create(infinitive: 'kneel', simple_past: 'knelt / knelled', past_participle: 'knelt / kneeled')
Verb.create(infinitive: 'know', simple_past: 'knew', past_participle: 'known')
Verb.create(infinitive: 'lay', simple_past: 'laid', past_participle: 'laid')
Verb.create(infinitive: 'lead', simple_past: 'led', past_participle: 'led')
Verb.create(infinitive: 'lean', simple_past: 'leant / leaned', past_participle: 'leant / leaned')
Verb.create(infinitive: 'leap', simple_past: 'leapt / leaped', past_participle: 'leapt / leaped')
Verb.create(infinitive: 'learn', simple_past: 'learnt', past_participle: 'learnt')
Verb.create(infinitive: 'leave', simple_past: 'left', past_participle: 'left')
Verb.create(infinitive: 'lend', simple_past: 'lent', past_participle: 'lent')
Verb.create(infinitive: 'let', simple_past: 'let', past_participle: 'let')
Verb.create(infinitive: 'lie', simple_past: 'lay', past_participle: 'lain')
Verb.create(infinitive: 'light', simple_past: 'lit / lighted', past_participle: 'lit / lighted')
Verb.create(infinitive: 'lose', simple_past: 'lost', past_participle: 'lost')
Verb.create(infinitive: 'make', simple_past: 'made', past_participle: 'made')
Verb.create(infinitive: 'mean', simple_past: 'meant', past_participle: 'meant')
Verb.create(infinitive: 'meet', simple_past: 'met', past_participle: 'met')
Verb.create(infinitive: 'mow', simple_past: 'mowed', past_participle: 'mowed / mown')
Verb.create(infinitive: 'offset', simple_past: 'offset', past_participle: 'offset')
Verb.create(infinitive: 'overcome', simple_past: 'overcame', past_participle: 'overcome')
Verb.create(infinitive: 'partake', simple_past: 'partook', past_participle: 'partaken')
Verb.create(infinitive: 'pay', simple_past: 'paid', past_participle: 'paid')
Verb.create(infinitive: 'plead', simple_past: 'pled / pleaded', past_participle: 'pled / pleaded')
Verb.create(infinitive: 'preset', simple_past: 'preset', past_participle: 'preset')
Verb.create(infinitive: 'prove', simple_past: 'proved', past_participle: 'proven / proved')
Verb.create(infinitive: 'put', simple_past: 'put', past_participle: 'put')
Verb.create(infinitive: 'quit', simple_past: 'quit', past_participle: 'quit')
Verb.create(infinitive: 'read', simple_past: 'read', past_participle: 'read')
Verb.create(infinitive: 'relay', simple_past: 'relaid', past_participle: 'relaid')
Verb.create(infinitive: 'rend', simple_past: 'rent', past_participle: 'rent')
Verb.create(infinitive: 'rid', simple_past: 'rid', past_participle: 'rid')
Verb.create(infinitive: 'ride', simple_past: 'rode', past_participle: 'ridden')
Verb.create(infinitive: 'ring', simple_past: 'rang', past_participle: 'rung')
Verb.create(infinitive: 'rise', simple_past: 'rose', past_participle: 'risen')
Verb.create(infinitive: 'run', simple_past: 'ran', past_participle: 'run')
Verb.create(infinitive: 'saw', simple_past: 'saw / sawed', past_participle: 'sawn / sawed')
Verb.create(infinitive: 'say', simple_past: 'said', past_participle: 'said')
Verb.create(infinitive: 'see', simple_past: 'saw', past_participle: 'seen')
Verb.create(infinitive: 'seek', simple_past: 'sought', past_participle: 'sought')
Verb.create(infinitive: 'sell', simple_past: 'sold', past_participle: 'sold')
Verb.create(infinitive: 'send', simple_past: 'sent', past_participle: 'sent')
Verb.create(infinitive: 'set', simple_past: 'set', past_participle: 'set')
Verb.create(infinitive: 'shake', simple_past: 'shook', past_participle: 'shaken')
Verb.create(infinitive: 'shed', simple_past: 'shed', past_participle: 'shed')
Verb.create(infinitive: 'shine', simple_past: 'shone', past_participle: 'shone')
Verb.create(infinitive: 'shoe', simple_past: 'shod', past_participle: 'shod')
Verb.create(infinitive: 'shoot', simple_past: 'shot', past_participle: 'shot')
Verb.create(infinitive: 'show', simple_past: 'showed', past_participle: 'shown')
Verb.create(infinitive: 'shut', simple_past: 'shut', past_participle: 'shut')
Verb.create(infinitive: 'sing', simple_past: 'sang', past_participle: 'sung')
Verb.create(infinitive: 'sink', simple_past: 'sank / sunk', past_participle: 'sunk / sunken')
Verb.create(infinitive: 'sit', simple_past: 'sat', past_participle: 'sat')
Verb.create(infinitive: 'slay', simple_past: 'slew', past_participle: 'slain')
Verb.create(infinitive: 'sleep', simple_past: 'slept', past_participle: 'slept')
Verb.create(infinitive: 'slide', simple_past: 'slid', past_participle: 'slid')
Verb.create(infinitive: 'slink', simple_past: 'slunk / slinked', past_participle: 'slunk / slinked')
Verb.create(infinitive: 'slit', simple_past: 'slit', past_participle: 'slit')
Verb.create(infinitive: 'smell', simple_past: 'smelt', past_participle: 'smelt')
Verb.create(infinitive: 'sow', simple_past: 'sowed', past_participle: 'sown / sowed')
Verb.create(infinitive: 'speak', simple_past: 'spoke', past_participle: 'spoken')
Verb.create(infinitive: 'speed', simple_past: 'sped', past_participle: 'sped')
Verb.create(infinitive: 'spell', simple_past: 'spelt', past_participle: 'spelt')
Verb.create(infinitive: 'spend', simple_past: 'spent', past_participle: 'spent')
Verb.create(infinitive: 'spill', simple_past: 'spilt / spilled', past_participle: 'spilt / spilled')
Verb.create(infinitive: 'spin', simple_past: 'spun', past_participle: 'spun')
Verb.create(infinitive: 'spit', simple_past: 'spat / spit', past_participle: 'spat / spit')
Verb.create(infinitive: 'split', simple_past: 'split', past_participle: 'split')
Verb.create(infinitive: 'spoil', simple_past: 'spoilt', past_participle: 'spoilt')
Verb.create(infinitive: 'spread', simple_past: 'spread', past_participle: 'spread')
Verb.create(infinitive: 'spring', simple_past: 'sprang', past_participle: 'sprung')
Verb.create(infinitive: 'stand', simple_past: 'stood', past_participle: 'stood')
Verb.create(infinitive: 'steal', simple_past: 'stole', past_participle: 'stolen')
Verb.create(infinitive: 'stick', simple_past: 'stuck', past_participle: 'stuck')
Verb.create(infinitive: 'sting', simple_past: 'stung', past_participle: 'stung')
Verb.create(infinitive: 'stink', simple_past: 'stank', past_participle: 'stunk')
Verb.create(infinitive: 'strew', simple_past: 'strewed', past_participle: 'strewn / strewed')
Verb.create(infinitive: 'strike', simple_past: 'struck', past_participle: 'stricken / struck')
Verb.create(infinitive: 'strive', simple_past: 'strove', past_participle: 'striven')
Verb.create(infinitive: 'swear', simple_past: 'swore', past_participle: 'sworn')
Verb.create(infinitive: 'sweat', simple_past: 'sweat / sweated', past_participle: 'sweat / sweated')
Verb.create(infinitive: 'sweep', simple_past: 'swept', past_participle: 'swept')
Verb.create(infinitive: 'swell', simple_past: 'swelled', past_participle: 'swollen / swelled')
Verb.create(infinitive: 'swim', simple_past: 'swam', past_participle: 'swum')
Verb.create(infinitive: 'swing', simple_past: 'swung', past_participle: 'swung')
Verb.create(infinitive: 'take', simple_past: 'took', past_participle: 'taken')
Verb.create(infinitive: 'teach', simple_past: 'taught', past_participle: 'taught')
Verb.create(infinitive: 'tear', simple_past: 'tore', past_participle: 'torn')
Verb.create(infinitive: 'tell', simple_past: 'told', past_participle: 'told')
Verb.create(infinitive: 'think', simple_past: 'thought', past_participle: 'thought')
Verb.create(infinitive: 'thrive', simple_past: 'throve / thrived', past_participle: 'thriven / thrived')
Verb.create(infinitive: 'throw', simple_past: 'threw', past_participle: 'thrown')
Verb.create(infinitive: 'thrust', simple_past: 'thrust', past_participle: 'thrust')
Verb.create(infinitive: 'tread', simple_past: 'trod', past_participle: 'trodden')
Verb.create(infinitive: 'typeset', simple_past: 'typeset', past_participle: 'typeset')
Verb.create(infinitive: 'undergo', simple_past: 'underwent', past_participle: 'undergone')
Verb.create(infinitive: 'understand', simple_past: 'understood', past_participle: 'understood')
Verb.create(infinitive: 'wake', simple_past: 'woke', past_participle: 'woken')
Verb.create(infinitive: 'wear', simple_past: 'wore', past_participle: 'worn')
Verb.create(infinitive: 'weep', simple_past: 'wept', past_participle: 'wept')
Verb.create(infinitive: 'wet', simple_past: 'wet / wetted', past_participle: 'wet / wetted')
Verb.create(infinitive: 'win', simple_past: 'won', past_participle: 'won')
Verb.create(infinitive: 'wind', simple_past: 'wound', past_participle: 'wound')
Verb.create(infinitive: 'withdraw', simple_past: 'withdrew', past_participle: 'withdrawn')
Verb.create(infinitive: 'wring', simple_past: 'wrung', past_participle: 'wrung')
Verb.create(infinitive: 'write', simple_past: 'wrote', past_participle: 'written')